import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./_layout/footer";
import { Header } from "./_layout/header";
import { Container } from "./_layout/container";

import { Main } from "./_layout/Main";
import { AuthContextProvider } from "./_layout/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AuthContextProvider>
          <Container>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </Container>
        </AuthContextProvider>
      </body>
    </html>
  );
}
