import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./_layout/footer";
import { Header } from "./_layout/header";
import { Container } from "./_layout/container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="">
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
