import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./_layout/footer";
import { Header } from "./_layout/header";
import { Container } from "./_layout/container";
import { AuthProvider } from "./_layout/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="">
        <AuthProvider>
          <Header />
          <Container>{children}</Container>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
